# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Petar Veličković
email: pv273@cam.ac.uk
description: > 
    My personal blog about computer science, music, gaming, and more. 
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://petarv-.github.io" # the base hostname & protocol for your site

main_heading: Petar Veličković
main_subheading: PhD student in Machine Learning and Bioinformatics

social:
    - title: Facebook
      url: https://facebook.com
      id: facebook

    - title: Twitter
      url: https://twitter.com
      id: twitter

    - title: LinkedIn
      url: https://linkedin.com
      id: linkedin

    - title: GitHub
      url: https://github.com
      id: github

    - title: CodeForces
      url: https://codeforces.com
      id: codeforces

    - title: TopCoder
      url: https://codeforces.com
      id: topcoder
          
categories_list:
    - Computer Science
    - Gaming
    - Music
    - TV Shows

# Build settings
markdown: kramdown
